# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-30 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomments',
            name='comments',
            field=models.CharField(default='', max_length=250, verbose_name='\u8bc4\u8bba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userask',
            name='course_name',
            field=models.CharField(default='', max_length=50, verbose_name='\u8bfe\u7a0b\u540d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userask',
            name='mobile',
            field=models.CharField(default='', max_length=11, verbose_name='\u624b\u673a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userask',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='\u59d3\u540d'),
        ),
    ]
