# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-30 00:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerCourse',
        ),
        migrations.AddField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='', max_length=20, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='course',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570'),
        ),
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('cj', '\u521d\u7ea7'), ('zj', '\u4e2d\u7ea7'), ('gj', '\u9ad8\u7ea7')], default='cj', max_length=2, verbose_name='\u96be\u5ea6'),
        ),
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.CharField(default='', max_length=300, verbose_name='\u8bfe\u7a0b\u63cf\u8ff0'),
        ),
        migrations.AddField(
            model_name='course',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='courses/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u8f6e\u64ad'),
        ),
        migrations.AddField(
            model_name='course',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u65f6\u957f(\u5206\u949f\u6570)'),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='\u8bfe\u7a0b\u540d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570'),
        ),
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=15, verbose_name='\u8bfe\u7a0b\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='\u6309\u65f6\u4ea4\u4f5c\u4e1a,\u4e0d\u7136\u53eb\u5bb6\u957f', max_length=300, verbose_name='\u8001\u5e08\u544a\u8bc9\u4f60'),
        ),
        migrations.AddField(
            model_name='course',
            name='you_need_know',
            field=models.CharField(default='\u4e00\u9897\u52e4\u5b66\u7684\u5fc3\u662f\u672c\u8bfe\u7a0b\u5fc5\u8981\u524d\u63d0', max_length=300, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8bfe\u7a0b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseresource',
            name='download',
            field=models.FileField(default='', upload_to='course/resource/%Y/%m', verbose_name='\u8d44\u6e90\u6587\u4ef6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseresource',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8bfe\u7a0b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='\u7ae0\u8282\u540d'),
        ),
        migrations.AddField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='\u7ae0\u8282'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='\u89c6\u9891\u540d'),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='http://blog.mtianyan.cn/', max_length=200, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
