# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-31 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180530_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail',
            field=models.TextField(default='', verbose_name='\u8bfe\u7a0b\u8be6\u60c5'),
            preserve_default=False,
        ),
    ]
